dataset:
  train_data_root_dir: "E:\\dataset\\ubfc-phys\\pos_rppg"
  test_data_root_dir: "E:\\dataset\\ubfc-phys\\processed\\test"
  frame_rate: 35
  T1_eliminated: ['s3', 's8', 's9', 's26', 's28', 's30', 's31', 's32', 's33', 's40', 's52', 's53', 's54', 's56']
  #["s7","s51","s48","s44","s42","s39","s34","s29","s47","s46","s25","s22","s2","s55","s45","s27","s21"]
  T2_eliminated: ['s1', 's4', 's6', 's8', 's9', 's11', 's12', 's13', 's14', 's19', 's21', 's22', 's25',
                  's26', 's27', 's28', 's31', 's32', 's33', 's35', 's38', 's39', 's41', 's42', 's45',
                  's47', 's48', 's52', 's53', 's55']
  #["s29","s44","s56","s50","s40","s7","s2","s30"]
  T3_eliminated: ['s5', 's8', 's9', 's10', 's13', 's14', 's17', 's22', 's25', 's26', 's28', 's30', 's32',
                  's33', 's35', 's37', 's40', 's47', 's48', 's49', 's50', 's52', 's53']
  #["s44","s34","s31","s29","s56","s45","s16","s11","s7","s55","s38","s21","s2"]
#  T1_selected: ['s1','s2','s4','s5','s6','s7','s10','s11','s12','s13','s14','s15','s16','s17','s18','s19','s20','s21',
#                's22','s23','s24','s25','s27','s29','s34','s35','s36','s37','s38','s39','s41','s42','s43','s44','s45',
#                's46','s47','s48','s49','s50','s51','s55']
#  T2_selected: ['s2','s3','s5','s7','s10','s15','s16','s17','s18','s20','s23','s24','s29','s30','s34','s36','s37','s40',
#                's43','s44','s46','s49','s50','s51','s54','s56']
#  T3_selected: ['s1','s2','s3','s4','s6','s7','s11','s12','s15','s16','s18','s19','s20','s21','s23','s24','s27','s29',
#                's31','s34','s36','s38','s39','s41','s42','s43','s44','s45','s46','s51','s54','s55','s56']
#  T1_selected: ['s1','s2','s4','s5','s6','s7','s10','s11','s12','s13','s14','s15','s16','s18','s19','s20','s21',
#                's22','s23','s24','s25','s27','s29','s34','s35','s36','s37','s38','s39','s41','s42','s43','s44','s45',
#                's46','s47','s48','s49','s50','s51','s55']
#  T2_selected: ['s2','s3','s5','s7','s10','s15','s16','s18','s20','s23','s24','s29','s30','s34','s36','s37','s40',
#                's43','s44','s46','s50','s51','s54','s56']
#  T3_selected: ['s1','s2','s3','s4','s6','s7','s11','s12','s15','s16','s18','s19','s20','s21','s23','s24','s27','s29',
#                's31','s34','s36','s38','s39','s41','s42','s43','s44','s45','s46','s51','s54','s55','s56']
  T1_selected: ['s1','s2','s4','s5','s6','s7','s10','s11','s12','s13','s14','s15','s16','s18','s19','s20','s21',
                's22','s23','s24','s25','s27','s29','s34','s35','s36','s37','s38','s39','s41','s42','s43','s44','s45',
                's46','s47','s48','s49','s50','s51','s55']
  T2_selected: ['s2','s3','s5','s7','s10','s15','s16','s18','s20','s23','s24','s29','s30','s34','s36','s37','s40',
                's43','s44','s46','s50','s51','s54','s56']
  T3_selected: ['s1','s2','s3','s4','s6','s7','s11','s12','s15','s16','s18','s19','s20','s21','s23','s24','s27','s29',
                's31','s34','s36','s38','s39','s41','s42','s43','s44','s45','s46','s51','s54','s55','s56']
train:
  seed: 123
  cv_times: 10
  cross_attn: False
  epoch: 100
  LR: 0.001
  device_list: [0]
  step: 1050
  clip_len: 2100
#  step: 2100
#  clip_len: 2100
  time_series_len: 30
  jump_num: 1
  drop_num: 175
  matrix_dim: 120
  hidden_size: 384
  lstm_hidden_size: 256
  lstm_num_layers: 2
  transformer_layers: 2
  transformer_head_num: 5
  num_classes: 2
  batch_size: 256
  num_workers: 1
  save_model: True
  save_path: "./trained_models"
  weight_hr: 1
  weight_pp: 0.75